name: Terraform Lambda Auth Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job para fazer o build e a compactação da lambda auth function.
  build-lambda:
    name: Build and Zip Lambda Auth function
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Build Lambda Auth function
      run: |
        chmod +x ./build_lambda.sh  # Garantir que o script tenha permissão de execução
        ./build_lambda.sh  # Executar o script que compila e move o arquivo

    # Debug: Verificar se o arquivo zip foi criado
    - name: List files in bin directory
      run: ls -alh ../bin  # Listar os arquivos para garantir que o bootstrap.zip foi criado

  # Job para verificação do terraform do lambda auth em pull requests e merge para a main e push da main 
  push-lambda:
    name: Terraform Verification and Push Lambda Auth
    runs-on: ubuntu-latest

    needs: build-lambda

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      # Inicializar, validar e aplicar o Terraform para o diretório terraform
      - name: Initialize Terraform for Lambda Auth
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform for Lambda Auth
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform for Lambda Auth
        #if: github.ref == 'refs/heads/main' # Executa apenas na branch main
        working-directory: terraform
        run: terraform plan -out=lambda-auth

      - name: Apply Terraform for Lambda Auth
        #if: github.ref == 'refs/heads/main' # Executa apenas na branch main
        working-directory: terraform
        run: terraform apply -auto-approve lambda-auth
